// Independently labelled snippets: keep these fixed when changing the detector.
export const languageSamples: Record<string, string> = {
	xml: '<!DOCTYPE html>\n<html><head><title>Example</title></head>\n<body><p class="greeting">Hello</p></body></html>',
	bash: '#!/bin/bash\nfor file in *.txt; do\n  echo "$file"\n  cat "$file"\ndone',
	c: '#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n  printf("Hello\\n");\n  return EXIT_SUCCESS;\n}',
	cpp: '#include <iostream>\n#include <vector>\nint main() {\n  std::vector<int> values{1, 2, 3};\n  for (const auto& value : values) std::cout << value << std::endl;\n}',
	csharp: 'using System;\nnamespace Example {\n  public class Program {\n    public static void Main(string[] args) {\n      Console.WriteLine("Hello");\n    }\n  }\n}',
	cypher: 'MATCH (person:Person)-[:KNOWS]->(friend)\nWHERE person.name = "Patrik"\nRETURN friend.name ORDER BY friend.name',
	css: '.card {\n  display: flex;\n  padding: 12px;\n  background-color: #fff;\n}\n.card:hover { color: red; }',
	markdown: '# Release notes\n\nThis is **important** and *useful*.\n\n- First item\n- Second item\n\n[Documentation](https://example.com)',
	diff: 'diff --git a/file.txt b/file.txt\n--- a/file.txt\n+++ b/file.txt\n@@ -1,2 +1,2 @@\n-old value\n+new value\n unchanged',
	ruby: 'require "json"\nclass Greeter\n  def initialize(name)\n    @name = name\n  end\n  def greet\n    puts "Hello #{@name}"\n  end\nend',
	go: 'package main\nimport "fmt"\nfunc main() {\n  names := []string{"Ada", "Linus"}\n  for _, name := range names { fmt.Println(name) }\n}',
	graphql: 'query GetUser($id: ID!) {\n  user(id: $id) {\n    id\n    name\n    friends { id name }\n  }\n}',
	ini: '[server]\nhost = localhost\nport = 8080\n[logging]\nenabled = true',
	java: 'import java.util.List;\npublic class Example {\n  public static void main(String[] args) {\n    List<String> names = List.of("Ada");\n    for (String name : names) System.out.println(name);\n  }\n}',
	javascript: 'export async function loadUsers(url) {\n  const response = await fetch(url);\n  const users = await response.json();\n  return users.map(user => ({ ...user, active: true }));\n}',
	json: '{\n  "name": "Example",\n  "enabled": true,\n  "items": [1, 2, 3],\n  "metadata": null\n}',
	kotlin: 'data class User(val name: String, val age: Int)\nfun main() {\n  val users = listOf(User("Ada", 30))\n  users.filter { it.age > 18 }.forEach { println(it.name) }\n}',
	less: '@accent: #336699;\n.rounded(@radius: 4px) { border-radius: @radius; }\n.card {\n  .rounded(8px);\n  color: @accent;\n  &:hover { color: lighten(@accent, 10%); }\n}',
	lua: 'local function greet(name)\n  if name ~= nil then\n    print("Hello " .. name)\n  end\nend\nfor i = 1, 3 do greet("friend") end',
	makefile: '.PHONY: all clean\nCC = gcc\nCFLAGS = -Wall -O2\nall: app\napp: main.c\n\t$(CC) $(CFLAGS) -o $@ $<\nclean:\n\trm -f app',
	perl: 'use strict;\nuse warnings;\nmy @names = ("Ada", "Linus");\nforeach my $name (@names) {\n  print "Hello $name\\n";\n}',
	objectivec: '#import <Foundation/Foundation.h>\n@interface Greeter : NSObject\n- (void)greet;\n@end\n@implementation Greeter\n- (void)greet { NSLog(@"Hello"); }\n@end',
	php: '<?php\nnamespace Example;\nfunction greet(string $name): string {\n  return "Hello " . $name;\n}\necho greet("Ada");',
	'php-template': '<html>\n<body>\n<?php foreach ($users as $user): ?>\n<p><?= htmlspecialchars($user->name) ?></p>\n<?php endforeach; ?>\n</body>\n</html>',
	plaintext: 'Det här är vanlig text som ska sparas i en anteckning.',
	python: 'from pathlib import Path\ndef read_names(filename):\n    with Path(filename).open() as stream:\n        return [line.strip() for line in stream if line.strip()]\nprint(read_names("names.txt"))',
	'python-repl': '>>> def greet(name):\n...     return f"Hello {name}"\n...\n>>> greet("Ada")\n\'Hello Ada\'',
	r: 'library(dplyr)\nvalues <- c(1, 2, 3, NA)\nmean_value <- mean(values, na.rm = TRUE)\nprint(mean_value)\ndata.frame(value = values)',
	rust: 'use std::collections::HashMap;\nfn main() {\n  let mut counts = HashMap::new();\n  counts.insert("hello", 1);\n  for (word, count) in &counts { println!("{}: {}", word, count); }\n}',
	scss: '$accent: #336699;\n@mixin rounded($radius: 4px) { border-radius: $radius; }\n.card {\n  @include rounded(8px);\n  color: $accent;\n  &:hover { color: lighten($accent, 10%); }\n}',
	shell: '$ ls -l\ntotal 0\n$ echo "Hello"\nHello\n$ pwd\n/home/user',
	sql: 'SELECT users.id, COUNT(orders.id) AS order_count\nFROM users\nLEFT JOIN orders ON orders.user_id = users.id\nWHERE users.active = TRUE\nGROUP BY users.id\nORDER BY order_count DESC;',
	swift: 'import Foundation\nstruct User {\n  let name: String\n  var age: Int\n}\nfunc greet(_ user: User) -> String {\n  return "Hello \\(user.name)"\n}\nlet user = User(name: "Ada", age: 30)',
	yaml: 'services:\n  web:\n    image: nginx:latest\n    ports:\n      - "8080:80"\n    environment:\n      DEBUG: true',
	typescript: 'interface User {\n  name: string;\n  age: number;\n}\nexport function greet(user: User): string {\n  return `Hello ${user.name}`;\n}',
	vbnet: 'Imports System\nModule Program\n  Sub Main()\n    Dim names As String() = {"Ada", "Linus"}\n    For Each name As String In names\n      Console.WriteLine(name)\n    Next\n  End Sub\nEnd Module',
	wasm: '(module\n  (func $add (param $a i32) (param $b i32) (result i32)\n    local.get $a\n    local.get $b\n    i32.add)\n  (export "add" (func $add))\n)',
};
